---
title: "Platform"
format: html
---

## Jeb Bush On the Issues!

#### I'm not pro "choice", I'm pro abortion

- No conservative litmus test for judicial appointments. (Nov 2015)
- Abortion ok when LIFE of mother at risk, not just her HEALTH. (Nov 2015)
- Defund Planned Parenthood, but not with federal shutdown. (Sep 2015)
- I defunded Planned Parenthood in Florida; do same federally. (Sep 2015)
- Husband of Terri Schiavo blames Bush for harassment. (Jan 2015)
- Terri Schiavo case: ordered feeding tube reinserted. (Feb 2014)
- OpEd: Jeb avoids extremism on women's issues. (Aug 2012)
- Funded adoption counseling, but not abortion counseling. (Dec 2009)
- Prevent use of public funds for stem cell research. (Dec 2009)
- Created divisive "Choose Life" license plates. (Feb 2007)
- Parental consent; clinic regulation; pro-life counseling. (Feb 2007)
- Restrict abortions to incest, rape, & health. (Jul 1998)
- No need to teach about abortion if we have moral absolutes. (Nov 1995)

#### It's the Economy, Stupid!

#### Civil rights? I don't listen to hiphop

#### Have you ever read "Atlas Shrugged"?

#### The 13th Amendment loophole

#### And on the 7th Day, God made all drugs

#### An illiterate citizen is a docile citizen

#### You love Big Oil, I hate nature, we're not the same

#### Love thy family as the Alamabans

#### Manifesting our destiny

#### It's the best/worst deal of the century

#### We're gonna win so big you won't have to vote again!

#### You gotta defend yourself, your family, your country!

#### Those hospital bills won't pay themselves, ya know?

#### See something? Say something!

#### Some, I believe, are good people

#### Recovering from Obama's Mistake

#### What is this conservatism thing?

#### Stick up those hands and gimme yer pensions

#### Some good ol'fashioned tax cuts (for my buddies)

#### Bow down to your AI Gods

#### Showing the Taliban American Firepower

#### Causing additional suffering to the already miserable